runs:
    using: "Composite"
    steps:
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
              node-version: "20.x"

        - name: Install node_modules
          run: npm ci
          shell: bash

        - name: vars -> .env
          run: |
              for var in $(printenv | cut -d "=" -f1); do
                  echo "$var=\"${!var}\"" >> ".env"
              done
          shell: bash
