name: Staging-Deploy

on:
    push:
        branches-ignore:
            - "main"
        paths:
            - "**"
    workflow_dispatch:
        branches-ignore:
            - "main"

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            TZ: "Asia/Tokyo"
        steps:
            - name: Setup repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"

            - name: Install node_modules
              run: npm ci

            - name: Test using jest
              run: |
                  npx jest --coverage

    deploy:
        needs: test
        runs-on: ubuntu-latest

        env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            ID_TOKEN: ${{ secrets.ID_TOKEN }}
            REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            SCRIPT_ID: ${{ secrets.STAGING_SCRIPT_ID }}
            DEPLOYMENT_ID: ${{ secrets.STAGING_DEPLOYMENT_ID }}

        steps:
            - name: Setup repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"

            - name: Install node_modules
              run: npm ci

            - name: Transpile ts -> js
              run: npx ts-node -T build.ts

            - name: Generate ~/.clasprc.json
              run: |
                  bash deployment/generate_clasprc.sh
            - name: Generate ~/.clasp.json
              run: |
                  bash deployment/generate_claspjson.sh
            - name: Push
              run: |
                  npx clasp push --force
            - name: DEPLOY
              run: |
                  npx clasp deploy --deploymentId $DEPLOYMENT_ID -d Staging
