name: Staging-Deploy

on:
    push:
        branches-ignore:
            - "main"
        paths:
            - "**"
    workflow_dispatch:
        branches-ignore:
            - "main"

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            TZ: "Asia/Tokyo"
        steps:
            - name: Setup repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"

            - name: Install node_modules
              run: npm ci

            - name: Test using jest
              run: |
                  npm run test

    deploy:
        needs: test
        runs-on: ubuntu-latest

        env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            ID_TOKEN: ${{ secrets.ID_TOKEN }}
            REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            SCRIPT_ID: ${{ secrets.STAGING_SCRIPT_ID }}
            DEPLOYMENT_ID: ${{ secrets.STAGING_DEPLOYMENT_ID }}

        steps:
            - name: Setup repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"

            - name: Install node_modules
              run: npm ci

            - name: vars -> .env
              run: |
                  touch .env
                  echo ACCESS_TOKEN=$ACCESS_TOKEN >> .env
                  echo ID_TOKEN=$ID_TOKEN >> .env
                  echo REFRESH_TOKEN=$REFRESH_TOKEN >> .env
                  echo CLIENT_ID=$CLIENT_ID >> .env
                  echo CLIENT_SECRET=$CLIENT_SECRET >> .env
                  echo SCRIPT_ID=$SCRIPT_ID >> .env
                  echo DEPLOYMENT_ID=$DEPLOYMENT_ID >> .env

            - name: DEPLOY
              run: |
                  npm run deploy
